### ISSUE TITLE
Write a blog post summarizing issue with SDL batching

### ISSUE THREAD

**Issue by no-more-secrets** [michaeladamkatz/misc#1]
Hi there,
Wasn't sure how else to get in touch other than submitting an issue here :)  I saw your posts here:

https://discourse.libsdl.org/t/confused-about-necessity-of-batch-rendering/24048/9

and I thought it would be nice if you could e.g. write a blog post or something about the whole thing, describing the problem and solution(s) that you found.  I am using SDL2 and ran into the same issue, but didn't understand what it was for a long time, and ended up wasting a lot of time/effort trying to solve it (by going in the wrong direction).

I bet this would save a lot of people a lot of time.

Though I should also ask: did you find a solution?  SDL_gpu?  other?  Did SDL2 ever add batching support?

**Comment by michaeladamkatz** [comment]
I've added my email address to my github profile: michael@makomatic.com

I had to take a break from the game stuff, but I'm getting back into it and currently looking into using https://github.com/bkaradzic/bgfx, which seems very promising. It is what I thought SDL was: a library that solves the hardest part of cross-platform game development, providing a rendering API on top of all the popular APIs, including Metal on iOS.

**Comment by no-more-secrets** [comment]
Ok -- and what did you end up doing in your game Cesaria?  I took at a look at the code and I see mention of `SDL_CreateBatch`... is that something that you wrote or is it part of SDL?

**Comment by michaeladamkatz** [comment]
Cesaria is not my game.

**Comment by no-more-secrets** [comment]
Ok -- anyway, thanks for the info.
